import streamlit as st

def init_lang():
    if 'lang' not in st.session_state:
        st.session_state.lang = 'th'

def switch_lang():
    st.session_state.lang = 'en' if st.session_state.lang == 'th' else 'th'

text = {
    'th' : {
        "title": "☀️ SOLAR OPTIMA",
        "subtitle": "ระบบคำนวณจุดติดตั้งสถานีชาร์จและวิเคราะห์ความเสี่ยงด้วย AI",
        "sidebar_settings": "⚙️ การตั้งค่าระบบ",
        "user_data": "📍 ข้อมูลพิกัดผู้ใช้งาน",
        "env_settings": "🌤️ สภาพแวดล้อม",
        "eng_settings": "🔧 ข้อมูลทางวิศวกรรม",
        "result_title": "📊 ผลการวิเคราะห์พื้นที่",
        "reliability": "ความมั่นใจของระบบ",
        "energy_req": "ความต้องการพลังงาน",
        "energy_gen": "พลังงานที่ผลิตได้",
        "loss": "พลังงานสูญเสีย",
        "lang_btn": "English",
        "season": "ฤดูกาล",
        "cloud": "สภาพท้องฟ้า",
        "sus_title": "🌱 การวิเคราะห์ความยั่งยืน",
        "co2_label": "ลดการปล่อยก๊าซเรือนกระจก",
        "co2_desc": "เทียบเท่ากับการปลูกต้นไม้เพื่อดูดซับคาร์บอน",
        "wire_label": "ลดการใช้ทรัพยากรสายไฟ",
        "wire_desc": "คำนวณจากระยะทางที่ลดลงจากจุดติดตั้งเดิม",
        "unit_co2": "kgCO2e/วัน",
        "unit_m": "เมตร",
        "summer": "ฤดูร้อน",
        "rainy": "ฤดูฝน",
        "winter": "ฤดูหนาว",
        "clear": "ท้องฟ้าแจ่มใส",
        "partial": "มีเมฆบางส่วน",
        "cloudy": "เมฆมาก",
        "sigma_label": "ความไม่แน่นอน",
        "forbidden_title": "🚫 กำหนดพื้นที่ห้ามติดตั้ง",
        "forbidden_help": "ระบุพิกัดมุม [Lat Min, Lat Max, Lon Min, Lon Max] (Optional)",
        "finance_title": "💰 การวิเคราะห์ความคุ้มทุน",
        "budget": "งบประมาณการติดตั้งประมาณการ",
        "payback": "ระยะเวลาคืนทุน",
        "currency": "บาท",
        "year": "ปี",
        "savings_year": "ประหยัดค่าไฟฟ้าได้ปีละ",
        "nav_home": "หน้าแรก",
        "nav_config": "ตั้งค่าระบบ",
        "nav_results": "ผลการวิเคราะห์",
        "btn_start": "เริ่มต้นใช้งานระบบ 🚀",
        "btn_analyze": "เริ่มการวิเคราะห์เชิงลึก 📊",
        "btn_back": "⬅️ กลับไปหน้าตั้งค่าระบบ",
        "home_desc": "แพลตฟอร์มการจำลองสถานการณ์และการคำนวณเชิงคณิตศาสตร์ขั้นสูง สำหรับการวางแผนพิกัดสถานีประจุไฟฟ้าพลังงานแสงอาทิตย์อย่างมีประสิทธิภาพสูงสุด แม่นยำ และตอบโจทย์ความยั่งยืนของชุมชน",
        "need_more_panels": "ต้องการแผงโซลาร์เซลล์เพิ่ม",
        "energy_sufficient": "พลังงานเพียงพอ",
        "mode_eff": "พิกัดโหมดประสิทธิภาพ",
        "mode_equ": "พิกัดโหมดเสมอภาค",
        "wire_desc": "ความยาวสายไฟรวม",
        "unit_m": "เมตร",
        "matrix_title": "ตารางเปรียบเทียบผลการคำนวณแต่ละโมเดล ",
        "metric_header": "เกณฑ์การวิเคราะห์",
        "obj_label": "เป้าหมายของฟังก์ชัน",
        "obj_equ": "ลดระยะทางเดินเท้าเฉลี่ยให้สั้นที่สุด",
        "obj_eff": "ลดการสูญเสียพลังงานในสายไฟฟ้าให้ต่ำที่สุด",
        "coord_label": "พิกัดที่ตั้งศูนย์กลาง",
        "loss_label": "พลังงานไฟฟ้าที่สูญเสีย",
        "unit_kwh": "kWh/วัน",
        "walk_label": "ระยะเดินเท้าเฉลี่ยผู้ใช้",
        "vdrop_label": "แรงดันไฟฟ้าตกในระบบ",
        "pass": "ผ่าน",
        "fail": "ไม่ผ่าน",
        "area_label": "พื้นที่แผงโซลาร์ที่ต้องการ",
        "unit_sqm": "ตร.ม." 
    },
    'en' : {
        "title": "☀️ SOLAR OPTIMA",
        "subtitle": "AI-Driven Charging Station Placement & Reliability Analysis",
        "sidebar_settings": "⚙️ System Configuration",
        "user_data": "📍 User Location Data",
        "env_settings": "🌤️ Environmental Conditions",
        "eng_settings": "🔧 Engineering Data",
        "result_title": "📊 Analysis Results",
        "reliability": "System Reliability",
        "energy_req": "Energy Demand",
        "energy_gen": "Energy Generated",
        "loss": "Energy Loss",
        "lang_btn": "ภาษาไทย",
        "season": "Season",
        "cloud": "Cloud Cover",
        "sus_title": "🌱 Sustainability Analysis",
        "co2_label": "GHG Reduction",
        "co2_desc": "Equivalent to tree planting for carbon sequestration",
        "wire_label": "Wire Resource Saving",
        "wire_desc": "Calculated from shorter distance compared to baseline",
        "unit_co2": "kgCO2e/day",
        "unit_m": "meters",
        "summer": "Summer",
        "rainy": "Rainy",
        "winter": "Winter",
        "clear": "Clear Sky",
        "partial": "Partially Cloudy",
        "cloudy": "Cloudy",
        "sigma_label": "Uncertainty",
        "forbidden_title": "🚫 Set Forbidden Zones",
        "forbidden_help": "Enter corners [Lat Min, Lat Max, Lon Min, Lon Max] (Optional)",
        "finance_title": "💰 Financial Analysis",
        "budget": "Estimated Investment",
        "payback": "Payback Period",
        "currency": "THB",
        "year": "Years",
        "savings_year": "Annual Savings",
        "nav_home": "Home",
        "nav_config": "Configuration",
        "nav_results": "Results",
        "btn_start": "Get Started 🚀",
        "btn_analyze": "Run Deep Analysis 📊",
        "btn_back": "⬅️ Back to Configuration",
        "home_desc": "An advanced mathematical modeling and optimization ecosystem designed to find the perfect coordination for solar charging stations, combining grid efficiency, community equity, and financial viability.",
        "need_more_panels": "Need More Panels",
        "energy_sufficient": "Energy Sufficient",
        "mode_eff": "Efficiency Mode Coordinates",
        "mode_equ": "Equity Mode Coordinates",
        "wire_desc": "Total Cable Length",
        "unit_m": "meters",
        "matrix_title": "Model Comparison Matrix",
        "metric_header": "Evaluation Metric",
        "obj_label": "Optimization Objective",
        "obj_equ": "Minimize average walking distance",
        "obj_eff": "Minimize system power loss",
        "coord_label": "Optimal Coordinates",
        "loss_label": "Total Energy Loss",
        "unit_kwh": "kWh/day",
        "walk_label": "Avg. Walking Distance",
        "vdrop_label": "Voltage Drop %",
        "pass": "Passed",
        "fail": "Failed",
        "area_label": "Required Solar Area",
        "unit_sqm": "m²"
    }
}

def get_text():
    init_lang()
    return text[st.session_state.lang]